[project]
name = "bing-translate"
version = "0.1.0"
description = "High-availability Bing Translator Python client with dynamic parameter extraction and local caching"
readme = "README.md"
authors = [
    { name = "zyp0714", email = "zyphndysq@outlook.com" }
]
requires-python = ">=3.10"
dependencies = [
    "brotli>=1.2.0",
    "requests>=2.34.2",
]

[project.scripts]
bing-translate = "Btrans.cli:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = "."
module-name = "Btrans"
